---
- name: Create app source directory
  sudo: yes
  file:
    path: "{{ accelerator['install_dir'] }}/{{ accelerator['name'] }}"
    state: directory
    mode: 0777

- name: "Add/Update app repo, using {{ app['version'] }}"
  git:
    repo: "{{ accelerator['repo']['url'] }}"
    dest: "{{ accelerator['install_dir'] }}/{{ accelerator['name'] }}"
    version: "{{ accelerator['repo']['version'] | default('master') }}"
    update: yes
    accept_hostkey: true
  notify: reload varnish
  tags:
    - release
  when: accelerator['repo'] is defined

- name: Disable Nginx default server
  sudo: yes
  command: "mv default.conf default.conf.off"
  args:
    chdir: "{{ nginx['server_root'] }}/conf.d"
    creates: "default.conf.off"
  notify: reload nginx
  when: accelerator["use_nginx"]
