---
- name: Create app source directory
  become: yes
  file:
    path: "{{ accelerator.install_dir }}/{{ accelerator.name }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775
  when: accelerator.repo

- name: "Add/Update app repo, using"
  git:
    repo: "{{ accelerator.repo.url }}"
    dest: "{{ accelerator.install_dir }}/{{ accelerator.name }}"
    version: "{{ accelerator.repo.version | default('master') }}"
    update: yes
    accept_hostkey: true
    force: yes
  notify:
    - reload varnish
    - reload nginx
  tags:
    - release
  when: accelerator.repo.url is defined
